# -*- coding: utf-8 -*-
"""Run every scripts/fig_*.py in a subprocess and report script -> pdf -> status.

Usage: python scripts/make_all_figures.py [--quick] [--no-cache] [--only fig_1 fig_3 ...]

Exit code 0 only if every script succeeds and writes its PDF (paper/figures/fig<n>_<name>.pdf,
derived from the script name scripts/fig_<n>_<name>.py).  With ``--quick`` the PDFs are expected
in paper/figures/quick/ (and summaries in data/quick/): the final figures are never touched.
"""
import argparse
import glob
import os
import re
import subprocess
import sys
import time

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
FIGDIR = os.path.join(ROOT, "paper", "figures")
QUICK_FIGDIR = os.path.join(FIGDIR, "quick")


def pdf_for(script, quick=False):
    """scripts/fig_<n>_<name>.py -> paper/figures[/quick]/fig<n>_<name>.pdf"""
    m = re.match(r"fig_(\d+)_(.+)\.py$", os.path.basename(script))
    if not m:
        return None
    return os.path.join(QUICK_FIGDIR if quick else FIGDIR, "fig%s_%s.pdf" % (m.group(1), m.group(2)))


# Figures of the short report (informe/), not of the manuscript: they write to informe/figures/
# and are regenerated by running them directly.
REPORT_ONLY = ("fig_9_pminflux_timing.py", "fig_10_background_bias.py")


def discover():
    scripts = glob.glob(os.path.join(HERE, "fig_*.py"))
    scripts = [s for s in scripts if pdf_for(s) is not None and os.path.basename(s) not in REPORT_ONLY]
    return sorted(scripts, key=lambda s: int(re.match(r"fig_(\d+)_", os.path.basename(s)).group(1)))


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--quick", action="store_true", help="pass --quick to every figure script")
    ap.add_argument("--no-cache", dest="no_cache", action="store_true", help="pass --no-cache")
    ap.add_argument("--only", nargs="*", default=None, help="run only scripts whose name starts with these")
    args = ap.parse_args(argv)

    scripts = discover()
    if args.only:
        scripts = [s for s in scripts if any(os.path.basename(s).startswith(o) for o in args.only)]
    if not scripts:
        print("no scripts/fig_*.py found")
        return 1
    flags = (["--quick"] if args.quick else []) + (["--no-cache"] if args.no_cache else [])
    rows = []
    for s in scripts:
        pdf = pdf_for(s, args.quick)
        t0 = time.time()
        before = os.path.getmtime(pdf) if os.path.exists(pdf) else None
        print("=== %s %s" % (os.path.basename(s), " ".join(flags)), flush=True)
        proc = subprocess.run([sys.executable, s] + flags, cwd=ROOT)
        dt = time.time() - t0
        fresh = os.path.exists(pdf) and (before is None or os.path.getmtime(pdf) > before)
        ok = proc.returncode == 0 and fresh
        status = "OK" if ok else ("FAIL (exit %d)" % proc.returncode if proc.returncode else "FAIL (no new pdf)")
        rows.append((os.path.basename(s), os.path.relpath(pdf, ROOT), status, dt))

    w1 = max(len(r[0]) for r in rows)
    w2 = max(len(r[1]) for r in rows)
    print("\n%-*s  %-*s  %8s  %s" % (w1, "script", w2, "pdf", "time[s]", "status"))
    for r in rows:
        print("%-*s  %-*s  %8.1f  %s" % (w1, r[0], w2, r[1], r[3], r[2]))
    n_bad = sum(1 for r in rows if r[2] != "OK")
    print("\n%d/%d figures OK" % (len(rows) - n_bad, len(rows)))
    return 1 if n_bad else 0


if __name__ == "__main__":
    sys.exit(main())
